site_name: pyControl
site_url: https://pycontrol.readthedocs.io/
site_description: Open source, Python based, behavioural experiment control.
site_author: Champalimaud Foundation

theme:
    name: readthedocs

repo_url: https://github.com/pycontrol/pycontrol-docs

nav:
- Home: index.md
- User Guide:
    - Graphical user interface (GUI): user-guide/graphical-user-interface.md
    - Command line interface (CLI): user-guide/command-line-interface.md
    - Programming tasks: user-guide/programming-tasks.md
    - Hardware: user-guide/hardware.md
    - Synchronisation: user-guide/synchronisation.md 
    - pyControl data: user-guide/pycontrol-data.md
    - Troubleshooting: user-guide/troubleshooting.md
- Contributing: contributing.md

- About:
    - Release Notes: about/release-notes.md
    - License: about/license.md

copyright: Copyright &copy; 2016 - 2019 Thomas Akam

