site_name: pyControl
site_url: https://pycontrol.readthedocs.io/
site_description: Controlling behavioural experiments with pyBoard
site_author: Champalimaud Foundation

theme: mkdocs

repo_url: https://bitbucket.org/fchampalimaud/pycontrol-docs

pages:
- Home: index.md
- User Guide:
    - Basic concepts: user-guide/basic-concepts.md 
    - Source code installation: user-guide/souce-code-installation.md
- About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

#extra_css:
#    - css/extra.css

#markdown_extensions:
#    - toc:
#        permalink: ÔÉÅ
#    - admonition:

copyright: Copyright &copy; 2016 <a href="/release-notes/">Champalimaud Foundation</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">Scientific Software Platform</a>.
#google_analytics: ['UA-27795084-5', 'mkdocs.org']
